### ISSUE TITLE
Opencrapers

### ISSUE THREAD

**Issue by Maju3** [I-A-C/repository.exodusredux#3]
Hi.
Just updated to exodus redux 2.0.1
The openscrapers modul does not load any link.
I have used exodus redux 1.7 with lambdascrapers and that has loaded tons of links perfectly.
I think openscrapers has a false list of german providers compared to the german providers list in lamdascrapers.

**Comment by Maju3** [comment]
Seems like the providers listed as German are actuall Greek providers.
In the foreign list of openscraper i mean.

**Comment by I-A-C** [comment]
Yea, I've put in a pull request to get this fixed.  Seems like GR is being used instead of DE for the language abbreviation.

**Comment by Maju3** [comment]
Okay cool.
Thank you

**Comment by Maju3** [comment]
Last update of openscraper solved this issue :)
